package controller;

import java.sql.SQLException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import controller.Notification;
import controller.NotificationRepository;
import database.Dashboard;

@Controller
@CrossOrigin(origins = "*")
@RequestMapping(path = "/notification") // This means URL's start with /demo (after Application path)
public class NotificationController {
	@Autowired // This means to get the bean called NotificationRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	//private NotificationRepository notificationRepository;

    @GetMapping(path = "/get")
	@ResponseBody
	public boolean getNotification(@RequestParam String username) throws SQLException, ClassNotFoundException {
		Dashboard dash = new Dashboard();
		boolean result = dash.getNotification(username);
		dash.close();
		return result;
	}

	@PostMapping(path = "/switch")
	@ResponseBody
	public void switchNotification(@RequestParam String username) throws SQLException, ClassNotFoundException {
		Dashboard dash = new Dashboard();
		dash.switchNotification(username);
		dash.close();
	}

}